import Head from "next/head";
import Image from "next/image";

import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="bg-[#181a1e] w-full min-h-screen">
      <Head>
        <title>Adam | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center">
        <div className="xl:max-w-[1280px] w-full">
          <Navbar />
        </div>
      </div>
    </div>
  );
}
