import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className=" w-full ">
      <Head>
        <title>Adam | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
}
